version: '3.7'
services:
    php8-sf6:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php8-sf6 
        ports:
            - "9000:8000"
        volumes:
            - .:/var/www/html

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: pizzas
            POSTGRES_PASSWORD: 1234
            POSTGRES_USER: root
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432"

volumes:
  db-data: